print(5+2 == 7)
print(5-2 == 3)
print(5*2 == 10)
print(5/2 == 2.5)
print(5**2 == 25)
print(5//2 == 2)
print(5 % 2 == 1)
print(81**(1/2))
# acima é o calculo da raiz quadrada
print(27**(1/3))
# acima é o calculo da raiz cúbica
print('oi '*5)
print('='*20)
name = input('Qual seu nome: ')
print('Muito prazer {:20}!'.format(name))
print('Muito prazer {:^20}!'.format(name))
print('Muito prazer {:<20}!'.format(name))
print('Muito prazer {:>20}!'.format(name))
print('Muito prazer {:=^20}!'.format(name))
n1 = int(input('um valor: '))
n2 = int(input('outro valor: '))
s = n1 + n2
print('A soma é', s, end=' - ')
print('A divisão \n n1 / n2 vale: {:.3f}'.format(n1/n2))
