x = (input('digite algo: '))
print(type(x))
print(x, ': é um número ?', x.isnumeric())
print(x, ': é uma letra ?', x.isalpha())
print(x, ': é um número / letra ?', x.isalnum())

m = input('Digite algo: ')

print(type(m))

print('é alphanumeric', m.isalnum())
print('é alphabetic', m.isalpha())
print('é ascii', m.isascii())
print('é decimal', m.isdecimal())
print('é digit', m.isdigit())
print('é identifier', m.isidentifier())
print('é slower', m.islower())
print('é numeric', m.isnumeric())
print('é printable', m.isprintable())
print('é space', m.isspace())
print('é title', m.istitle())
print('é upper', m.isupper())
