t = int(input('Digite 1 número de 1 até 10: '))
x = 1
print('-'*12)
print('{} x {:2} = {}'.format(t, x+0, t*(x+0)))
print('{} x {:2} = {}'.format(t, x+1, t*(x+1)))
print('{} x {:2} = {}'.format(t, x+2, t*(x+2)))
print('{} x {:2} = {}'.format(t, x+2, t*(x+3)))
print('{} x {:2} = {}'.format(t, x+4, t*(x+4)))
print('{} x {:2} = {}'.format(t, x+5, t*(x+5)))
print('{} x {:2} = {}'.format(t, x+6, t*(x+6)))
print('{} x {:2} = {}'.format(t, x+7, t*(x+7)))
print('{} x {:2} = {}'.format(t, x+8, t*(x+8)))
print('{} x {:2} = {}'.format(t, x+9, t*(x+9)))
print('-'*12)
